### ISSUE TITLE
pp and strong major countries

### ISSUE THREAD

**Issue by Likuatontid** [AdamDX1337/SilverHookDX11#1]
A very strong innovation in the cheat will be the implementation of strengthening major countries, this function is in JewishTricks and it can strengthen any major country by incredible percentages and this works in multiplayer.
And also somehow implement a change in political power, stability and support for war, as is implemented in JewishTricks.

**Comment by AdamDX1337** [comment]
This is what multiplayer lobby hack does

**Comment by Likuatontid** [comment]
Game crashes after activating Multiplayer lobby hack
